# Generated by Django 2.0.6 on 2018-06-19 11:30

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suinanjiko',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField()),
                ('ym', models.IntegerField()),
                ('pref', models.CharField(max_length=20)),
                ('river', models.CharField(max_length=50)),
                ('jiko', models.CharField(max_length=250)),
                ('accurate', models.CharField(max_length=250)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
